### ISSUE TITLE
Mongo数据库地址问题

### ISSUE THREAD

**Issue by RavelloH** [lrhtony/pixiv#6]
您好，请问在vercel配置环境变量的时候，所需要填写的`MONGO_URI`是以下格式的吗？
```
mongodb+srv://<数据库用户名>:<数据库密码>@<数据库名>.ufrwi9q.mongodb.net/?retryWrites=true&w=majority
```
我填写了这个格式的，但是在使用的时候提示函数崩溃，以下是vercel中的日志：
```
[ERROR] ConfigurationError: unknown storage scheme : ac-zelegv1-shard-00-01.ufrwi9q.mongodb.net:27017
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/vc__handler__python.py", line 13, in <module>
    __vc_spec.loader.exec_module(__vc_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./api/index.py", line 33, in <module>
    limiter = Limiter(
  File "/var/task/flask_limiter/extension.py", line 266, in __init__
    self.init_app(app)
  File "/var/task/flask_limiter/extension.py", line 311, in init_app
    storage_from_string(
  File "/var/task/limits/storage/__init__.py", line 62, in storage_from_string
    raise ConfigurationError("unknown storage scheme : %s" % storage_string)[ERROR] ConfigurationError: unknown storage scheme : ac-zelegv1-shard-00-01.ufrwi9q.mongodb.net:27017
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/vc__handler__python.py", line 13, in <module>
    __vc_spec.loader.exec_module(__vc_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./api/index.py", line 33, in <module>
    limiter = Limiter(
  File "/var/task/flask_limiter/extension.py", line 266, in __init__
    self.init_app(app)
  File "/var/task/flask_limiter/extension.py", line 311, in init_app
    storage_from_string(
  File "/var/task/limits/storage/__init__.py", line 62, in storage_from_string
    raise ConfigurationError("unknown storage scheme : %s" % storage_string)START RequestId: 53f22fca-40c2-46d9-8908-c2af77aa75dd Version: $LATEST
Unknown application error occurred
Runtime.Unknown
```

**Comment by lrhtony** [comment]
是的完整的uri包括前面的协议头
这个报错是Limiter模块的报错，说不知道存储方式，可以检查一下复制的时候是否漏了一些部分，或者有没有换行空格隐藏字符等导致截断了uri

**Comment by RavelloH** [comment]
> 是的完整的uri包括前面的协议头 这个报错是Limiter模块的报错，说不知道存储方式，可以检查一下复制的时候是否漏了一些部分，或者有没有换行空格隐藏字符等导致截断了uri

解决了，感谢！
